/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    signing
    `java-library`
    `maven-publish`
    kotlin("jvm")
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    api(libs.net.dv8tion.jda)
    api(libs.club.minnced.discord.webhooks)
    api(libs.org.json.json)
    api(libs.org.postgresql.postgresql)
    api(libs.com.github.twitch4j.twitch4j)
    api(libs.com.github.philippheuer.events4j.events4j.handler.reactor)
    api(libs.com.google.apis.google.api.services.youtube)
    api(libs.ch.qos.logback.logback.classic)
    api(libs.org.slf4j.slf4j.api)
    api(libs.com.zaxxer.hikaricp)
    api(libs.org.springframework.boot.spring.boot)
    api(libs.org.springframework.boot.spring.boot.autoconfigure)
    api(libs.org.springframework.spring.web)
    api(libs.org.springframework.boot.spring.boot.starter.tomcat)
    api(libs.org.springframework.boot.spring.boot.actuator)
    api(libs.org.springframework.boot.spring.boot.starter.data.rest)
    api(libs.com.squareup.okhttp3.okhttp)
    api(libs.org.jetbrains.annotations)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)

}

group = "de.sparkarmy"
version = "2.0-SNAPSHOT"
description = "SparkArmyBot"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
kotlin {
    jvmToolchain(21)
}