[versions]
jda-core = "6.4.1"
jda-freya-bc = "3.1.0"
postgres = "42.7.8"
hikari = "7.0.2"
aedile = "3.0.1"
kotlin-bom = "2.3.0"
data-caffeine = "3.2.4"
flyway = "11.20.0"
exposed-bom = "1.1.1"
logback-classic = "1.5.23"
slf4j-api = "2.0.17"
kotlin-logging-jvm = "7.0.13"


[libraries]
jda-core = { module = "net.dv8tion:JDA", version.ref = "jda-core" }
jda-bc-core = { module = "io.github.freya022:BotCommands", version.ref = "jda-freya-bc"}
jda-bc-ktx = { module = "io.github.freya022:BotCommands-jda-ktx", version.ref = "jda-freya-bc"}
jda-bc-restart = {module = "io.github.freya022:BotCommands-restarter", version.ref = "jda-freya-bc"}
jda-bc-typesafe-core = { module = "io.github.freya022:BotCommands-typesafe-messages-core",version.ref = "jda-freya-bc"}
jda-bc-typesafe-runtime = { module = "io.github.freya022:BotCommands-typesafe-messages-bc", version.ref = "jda-freya-bc"}

data-postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
data-hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
data-flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
data-flyway-database = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
data-caffeine = {module = "com.github.ben-manes.caffeine:caffeine",version.ref = "data-caffeine"}
data-exposed-bom = { module = "org.jetbrains.exposed:exposed-bom", version.ref = "exposed-bom" }
data-aedile = { module = "com.sksamuel.aedile:aedile-core", version.ref = "aedile" }
data-exposed-core = { module = "org.jetbrains.exposed:exposed-core" }
data-exposed-crypt = { module = "org.jetbrains.exposed:exposed-crypt" }
data-exposed-dao = { module = "org.jetbrains.exposed:exposed-dao" }
data-exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc" }
data-exposed-json = { module = "org.jetbrains.exposed:exposed-json" }
data-exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime" }

logging-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
logging-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
logging-kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging-jvm" }

[bundles]
jda = ["jda-core","jda-bc-ktx", "jda-bc-core","jda-bc-restart","jda-bc-typesafe-core"]
data = ["data-postgresql","data-hikari","data-flyway-core", "data-flyway-database","data-aedile","data-caffeine"]
data-exposed = ["data-exposed-core", "data-exposed-crypt", "data-exposed-dao", "data-exposed-jdbc", "data-exposed-json", "data-exposed-kotlin-datetime"]
logging = ["logging-kotlin-logging-jvm","logging-logback-classic","logging-slf4j-api"]


[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-bom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-bom" }


